---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alei5901/spicemixes.nl

    # Copy only files from the public folder to the deployment path
    - /bin/find public -maxdepth 1 -type f -exec /bin/cp {} $DEPLOYPATH/ \;

    # Copy the build folder to the deployment path
    - /bin/cp -a public/build/* $DEPLOYPATH/build

      # Copy other folders to the deployment path
    - /bin/cp -a app/* /home/alei5901/spicemixes/app
    - /bin/cp -a config/* /home/alei5901/spicemixes/config
    - /bin/cp -a routes/* /home/alei5901/spicemixes/routes
    - /bin/cp -a resources/* /home/alei5901/spicemixes/resources
    - /bin/cp -a public/* /home/alei5901/spicemixes/public
    - /bin/cp -a bootstrap/* /home/alei5901/spicemixes/bootstrap
