---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alei5901/spicemixes.nl/build

    # Install dependencies (if needed)
    #  - npm ci

    # Build the Svelte app
    # - npm run build

    # Copy the build folder to the deployment path
    - /bin/cp -a build/* $DEPLOYPATH
