---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alei5901/spicemixes.nl

    # Copy only files from the public folder to the deployment path, except for index.php (we need our custom index.php file)

    # Copy the build folder to the deployment path
    - /bin/cp -a public/build/* $DEPLOYPATH/build
    - /bin/cp -a public/vendor/telescope/* $DEPLOYPATH/vendor/telescope
    - /bin/find public -maxdepth 1 -type f ! -name "index.php" -exec /bin/cp {} $DEPLOYPATH/ \;

      # Copy other folders to the deployment path
    - /bin/cp -a app/* /home/alei5901/spicemixes/app
    - /bin/cp -a config/* /home/alei5901/spicemixes/config
    - /bin/cp -a routes/* /home/alei5901/spicemixes/routes
    - /bin/cp -a resources/* /home/alei5901/spicemixes/resources
    - /bin/cp -a public/build/manifest.json /home/alei5901/spicemixes/public/build/manifest.json
    - /bin/cp -a bootstrap/* /home/alei5901/spicemixes/bootstrap
    - /bin/cp -a database/* /home/alei5901/spicemixes/database
    - /bin/cp -a composer.json /home/alei5901/spicemixes/composer.json
    - /bin/cp -a composer.json /home/alei5901/spicemixes/composer.lock
    # below didnt work because contents are gitignored
    #- /bin/cp -a storage/app/public/* /home/alei5901/spicemixes/storage/app/public
